config/routes.rb
Rails.application.routes.draw do
  root to: 'static_pages#home'
  get 'login', to: 'user_sessions#new', as: :login
  delete 'logout', to: 'user_sessions#destroy', as: :logout
  post 'clip', to: "recipes#clip"

  resources :users, except: [:index, :show]
  resources :user_sessions
  resources :recipes do
    member do
      post "star", action: :star
      post "unstar", action: :unstar
    end
    collection do
      get "starred", action: :starred_index
    end
  end

end

app/models/recipe.rb
# == Schema Information
#
# Table name: recipes
#
#  id             :integer          not null, primary key
#  title          :string
#  author_name    :string
#  ref_url        :string
#  main_photo_url :string
#  description    :string
#  servings_for   :string
#  created_at     :datetime         not null
#  updated_at     :datetime         not null
#  image          :string
#  user_id        :integer
#  is_public      :boolean          default(FALSE), not null
#

class Recipe < ActiveRecord::Base
  acts_as_taggable_on :tags
  acts_as_votable
  belongs_to :users

  has_many :recipe_ingredients, -> { order(:row_order) }, dependent: :destroy
  accepts_nested_attributes_for :recipe_ingredients, allow_destroy: true

  has_many :recipe_steps, -> { order(:row_order) }, dependent: :destroy
  accepts_nested_attributes_for :recipe_steps, allow_destroy: true

  mount_uploader :image, ImageUploader

  validates :title, presence: true, length: {minimum: 2, maximum: 50}

  def is_public_and_created_by_others
    is_public && user_id != current_user
  end

  def is_clipped?
    ref_url.present?
  end
end

app/controllers/recipes_controller.rb
# == Schema Information
#
# Table name: recipes
#
#  id             :integer          not null, primary key
#  title          :string
#  author_name    :string
#  ref_url        :string
#  main_photo_url :string
#  description    :string
#  servings_for   :string
#  created_at     :datetime         not null
#  updated_at     :datetime         not null
#  image          :string
#  user_id        :integer
#  is_public      :boolean          default(FALSE), not null
#

class RecipesController < ApplicationController
  before_action :set_recipe, only: [:edit, :update, :destroy, :show, :star, :unstar]
  before_action :set_is_public, only: [:index, :show, :starred_index]
  before_action :is_self_owned, only: [:edit, :update, :destroy]
  before_action :is_self_owned_or_public, only: [:show]
  skip_before_action :require_login, only: [:show, :index]

  def index
    @q = Recipe.ransack(params[:q])
    if @is_public || !current_user
      # みんなのレシピ
      @recipes = @q.result(distinct: true).where(is_public: true)
      @recipes = @recipes.where.not(user_id: current_user.id) if current_user
    else
      # マイレシピ
      @recipes = @q.result(distinct: true).where(user_id: current_user.id)
      # 検索結果ではないばあい、お気に入り登録したレシピを追加（重複は排除）
      unless params[:q].present?
        @recipes = array_to_relations(
          [@recipes,  current_user.find_voted_items], Recipe
        )
      end
    end
    set_all_tags(@recipes)
    @recipes = @recipes.page(params[:page])
    @recipes = @recipes.tagged_with(params[:tag]) if params[:tag]
  end

  def starred_index
    @recipes = array_to_relations([current_user.find_voted_items], Recipe)
    set_all_tags(@recipes)
    @recipes = @recipes.page(params[:page])
  end

  def new
    @recipe = current_user.recipes.new
    @recipe.recipe_ingredients.build.row_order = 1 # new ではなく build
    @recipe.recipe_steps.build.row_order = 1 # new ではなく build
  end

  def create
    @recipe = current_user.recipes.new(recipe_params)
    if @recipe.save
        flash[:notice] = "レシピを保存しました。"
        redirect_to @recipe
    else
        flash[:alert] = "レシピの保存に失敗しました。"
        render :new
    end
  end

  def edit
  end

  def show
  end

  def destroy
    if @recipe.destroy
      flash[:notice] = "レシピを削除しました。"
      redirect_to root_path
    else
      flash[:alert] = "レシピの削除に失敗しました。"
      # えっと？
    end
  end

  def clip
    url = params[:clip_url]
    # view_context経由でヘルパーメソッドの呼び出し
    clipper = view_context.create_clipper(url)
    if clipper.present?
      @recipe = current_user.recipes.new(clipper.recipe_params)
      if @recipe.save
          flash[:notice] = "外部レシピを取得して保存しました。"
          redirect_to @recipe
      else
          flash[:alert] = "外部レシピを取得しましたが、保存に失敗しました。"
          render :new
      end
    else
      flash[:alert] = "外部レシピデータが取得できませんでした。URLを確認してください。"
      redirect_to new_recipe_path
    end
  end

  def update
    if @recipe.update(recipe_params)
      flash[:notice] = "レシピを更新しました。"
      redirect_to @recipe
    else
      flash[:alert] = "レシピの更新に失敗しました。"
      render :edit
    end
  end

  def star
    @recipe.liked_by current_user if current_user
  end

  def unstar
    @recipe.unliked_by current_user if current_user
  end

  private

  def set_recipe
    @recipe = Recipe.find(params[:id])
  end

  def set_is_public
    @is_public = (params.try(:[], :recipe).try(:[], :is_public)) == "true"
  end

  def set_all_tags(recipes)
    @tags = Set.new
    recipes.each { |recipe| @tags.merge(recipe.tag_list) }
  end

  def is_self_owned
    redirect_to root_path unless @recipe.user_id == current_user.id
  end

  def is_self_owned_or_public
    redirect_to root_path unless @recipe.is_public || @recipe.user_id == current_user.id
  end

  # ActiveRecord::Relation と 配列 を結合して Relation として返す
  # acts_as_votable のメソッドが配列を返してくるため、苦肉の策
  def array_to_relations relations, klass
    ids = Array.new
    relations.each { |rel|
      ids.concat rel.map{ |r| r.id }
    }
    klass.where(id: ids.uniq)
  end

  def recipe_params
    params.require(:recipe).permit(:id, :user_id, :title, :author_name, :ref_url,
      :main_photo_url, :description, :servings_for,
      :image, :image_cache, :remove_image, :clip_url, :tag_list,
      :tag, :is_public,
      recipe_ingredients_attributes: [:id, :name, :quantity_for,
        :order, :row_order, :_destroy],
      recipe_steps_attributes: [:id, :text, :photo_url, :position, :row_order,
        :image, :remove_image, :image_cache, :_destroy])
  end
end

app/helpers/recipes_helper.rb
# == Schema Information
#
# Table name: recipes
#
#  id             :integer          not null, primary key
#  title          :string
#  author_name    :string
#  ref_url        :string
#  main_photo_url :string
#  description    :string
#  servings_for   :string
#  created_at     :datetime         not null
#  updated_at     :datetime         not null
#  image          :string
#  user_id        :integer
#  is_public      :boolean          default(FALSE), not null
#

module RecipesHelper

  def tag_with_link_to(tag, is_public)
    link_to recipes_path(recipe: { is_public: is_public }, tag: tag) do
      content_tag :span, class: "tag label label-success" do
        tag
      end
    end
  end

  def is_from_action(action_name)
    controller.action_name == action_name
  end

  def is_public_view
    controller.action_name == "public_index"
  end

  def recipe_created_by_other_user? recipe
    recipe.user_id != current_user.try(:id)
  end

  require 'open-uri'
  require 'nokogiri'

  # 抽象クラス
  class Clipper

    def initialize(url)
      @url = url
    end

    def recipe_params
      param = get_recipe
      param[:recipe_ingredients_attributes] = get_ingredients
      param[:recipe_steps_attributes] = get_steps
      param
    end

    def get_recipe
    end

    def get_ingredients
    end

    def get_steps
    end

    protected

    def get_content(tag_css, element = nil)
      clip if !element && !@doc
      element = element ||= @doc
      element = element.css(tag_css).first
      element.present? ? sanitize_ex(element.inner_html) : nil
    end

    def get_attr(tag_css, attr_name, element = nil)
      clip if !element && !@doc
      element = element ||= @doc
      element.css(tag_css).first.try(:attr, attr_name)
    end

    def get_elements(tag_css)
      clip if !@doc
      @doc.css(tag_css)
    end

    def sanitize_ex(line)
      ActionController::Base.helpers.sanitize(line.gsub(/\n/,""), tags: ['br']).gsub(/<br.*?>/,"\n").gsub(/^\s*|\s*$/, "")
    end

    def clip
      charset = nil
      begin
        html = open(@url) do |f|
          charset = f.charset #文字種別を取得
          f.read #htmlを読み込んで変数htmlに渡す
        end
        #htmlをパース(解析)してオブジェクトを作成
        @doc = Nokogiri::HTML.parse(html, nil, charset)
      rescue OpenURI::HTTPError => e
        if e.message == '404 Not Found'
          # handle 404 error
        else
          raise e
        end
      end
    end
  end

  # Cookpadさん
  class CookpadClipper < Clipper
    def get_recipe
      title = get_content("h1.recipe-title")
      description = get_content(".summary .description_text")
      /（(.*?)）/ =~ get_content(".servings_for")
      servings_for = $1
      author_name = get_content("#recipe_author_name")
      main_photo_url = get_attr("#main-photo img", "data-large-photo")
      {title: title, description: description, author_name: author_name,
        ref_url: @url, servings_for: servings_for, remote_image_url: main_photo_url}
    end

    def get_ingredients
      arr_params = Array.new
      get_elements("div.ingredient_row").each do |e|
        # スペーサーやカテゴリをスキップ
        if e.css("div.ingredient_name").present?
          name = get_content("div.ingredient_name span.name", e)
          quantity_for = get_content("div.ingredient_quantity", e)
          # remote_image_url: carrierwave 経由で画像をダウンロード
          arr_params.push({name: name, quantity_for: quantity_for, row_order: arr_params.length + 1})
        end
      end
      arr_params
    end

    def get_steps
      arr_params = Array.new
      get_elements("div.step, div.step_last").each do |e|
        row_order = e.attr("data-position")
        text = get_content("p.step_text", e)
        photo_url = get_attr("div.image img", "data-large-photo", e)
        # remote_image_url: carrierwave 経由で画像をダウンロード
        arr_params.push({text: text, remote_image_url: photo_url, row_order: row_order})
      end
      arr_params
    end
  end

  # 楽天レシピさん
  class RakutenClipper < Clipper
    def get_recipe
      title = get_content("div.detailHead h1[itemprop=name]")
      description = get_content("div.detailArea p.summary")
      servings_for = get_content("div.materialBox span[itemprop=recipeYield]")
      author_name = get_content("div.ownerThumb span[itemprop=name]")
      main_photo_url = get_attr("div.rcpPhotoBox img", "src")
      {title: title, description: description, author_name: author_name,
        ref_url: @url, servings_for: servings_for, remote_image_url: main_photo_url}
    end

    def get_ingredients
      arr_params = Array.new
      get_elements("li[itemprop=ingredients]").each do |e|
          name = get_content("a", e)
          quantity_for = get_content("p.amount", e)
          # remote_image_url: carrierwave 経由で画像をダウンロード
          arr_params.push({name: name, quantity_for: quantity_for, row_order: arr_params.length + 1}) if name.present?
      end
      arr_params
    end

    def get_steps
      arr_params = Array.new
      get_elements("li.stepBox").each do |e|
        row_order = get_content("h4", e).to_i
        text = get_content("p.stepMemo", e)
        photo_url = get_attr("div.stepPhoto img", "src", e)
        # remote_image_url: carrierwave 経由で画像をダウンロード
        arr_params.push({text: text, remote_image_url: photo_url, row_order: row_order})
      end
      arr_params
    end
  end

  # オレンジページさん
  class OrangepageClipper < Clipper
    def get_recipe
      title = get_content("h1.title").strip
      description = get_content("p[itemprop=summary]").strip
      /（(.*?)）/ =~ get_content("div.recipeDetailFoodsList h2")
      servings_for = $1
      author_name = get_content("span[itemprop=author]")
      main_photo_url = get_attr("img[itemprop=photo]", "src")
      {title: title, description: description, author_name: author_name,
        ref_url: @url, servings_for: servings_for, remote_image_url: main_photo_url}
    end

    def get_ingredients
      arr_params = Array.new
      get_elements("li[itemprop=ingredient]").each do |e|
          name = get_content("span[itemprop=name]", e)
          quantity_for = get_content("span[itemprop=amount]", e)
          arr_params.push({name: name, quantity_for: quantity_for, row_order: arr_params.length + 1}) if name.present?
      end
      arr_params
    end

    def get_steps
      arr_params = Array.new
      i = 0
      get_elements("div[itemprop=instructions] div.direction").each do |e|
        row_order = i += 1
        # 説明文がdiv.direction の子要素になっていない
        text = sanitize_ex(e.next_element.inner_html)
        photo_url = nil # 画像なし
        # remote_image_url: carrierwave 経由で画像をダウンロード
        arr_params.push({text: text, remote_image_url: photo_url, row_order: row_order})
      end
      arr_params
    end
  end

  require 'net/http'
  require 'addressable/uri'

  def create_clipper(url)

    uri = Addressable::URI.parse(url)
    # check if URL Valid
    return nil if uri.host.nil?
    # remove params
    uri.query_values = nil
    # check is recipe URL
    recipe_url = "#{uri.scheme}://#{uri.host}#{uri.request_uri}"
    if (recipe_url =~ /^#{uri.scheme}:\/\/cookpad\.com\/recipe\/\d.*/).present?
      type = :cookpad
    elsif (recipe_url =~ /^#{uri.scheme}:\/\/www\.orangepage\.net\/recipes\/detail_\d.*/).present?
      type = :orangepage
    elsif (recipe_url =~ /^#{uri.scheme}:\/\/recipe\.rakuten\.co\.jp\/recipe\/\d.*/).present?
      type = :rakuten
    else
      return nil
    end

    # check if page really exists
    is_use_ssl = uri.scheme == "https"
    Net::HTTP.start(uri.host, uri.port, use_ssl: is_use_ssl) do |http|
      return nil if http.head(uri.request_uri).code != "200"
    end

    if type == :cookpad
      return CookpadClipper.new(recipe_url)
    elsif type == :orangepage
      return OrangepageClipper.new(recipe_url)
    elsif type == :rakuten
      return RakutenClipper.new(recipe_url)
    end

    return nil

  end
end

app/views/recipes/_clip_form.html.slim
= form_tag "/clip", class: "form-horizontal" do
  h3 レシピサービスからレシピを取得
  p 現在、<a href="http://cookpad.com" target="_blank">Cookpad</a>、<a href="http://recipe.rakuten.co.jp" target="_blank">楽天レシピ</a>、<a href="http://www.orangepage.net" target="_blank">オレンジページ.net</a>に対応しています。
  .form-group
    = label_tag :clip_url, "URL", class: "control-label col-md-2"
    .col-md-8
      = text_field_tag :clip_url, nil, class: "form-control"
    .col-md-2
      = submit_tag "取得する", class: "btn btn-success", \
        data: {toggle: "modal", target: "#modal", backdrop: "static"}

= render "modal_dialog"

app/views/recipes/_label_form.html.slim
.form-horizontal
  .form-group
    - if @tags.present?
      /label class="control-label col-md-2"
        | ラベルで検索
      .col-md-12.tags
        = link_to "すべてのレシピ", recipes_path(recipe: { is_public: @is_public }), class: "tag label label-info"
        - @tags.each do |tag|
          = tag_with_link_to tag, @is_public

app/views/recipes/_modal_dialog.html.slim
.modal.fade id="modal" role="dialog" aria-labelledby="gridSystemModalLabel"
  .modal-dialog role="document"
    .modal-content
      .modal-body
        h4 レシピデータを取得中です…

app/views/recipes/_recipe_form.html.slim
= render 'shared/error_messages', record: @recipe

= form_for @recipe, html: {class: "form-horizontal"} do |f|
  = f.hidden_field :id

  h2 レシピ情報
  .recipe
    .form-group
      = f.label :title, "タイトル", class: "col-md-2 control-label"
      .col-md-10
        = f.text_field :title, class: "form-control"

    .form-group
      = f.label :description, "概要", class: "col-md-2 control-label"
      .col-md-10
        = f.text_area :description, class: "form-control", rows: 5

    .form-group
      = f.label :servings_for, "分量", class: "col-md-2 control-label"
      .col-md-10
        = f.text_field :servings_for, class: "form-control"

    .form-group
      = f.label :image, "画像", class: "col-md-2 control-label"
      .col-md-10
        - if @recipe.image.present?
          = image_tag @recipe.image_url
          .image_related
            = f.check_box :remove_image
            = f.label :remove_image, "画像を削除", class: "control-label"
            / レシピの取得に成功したがデータに不足がある場合、
            / 新規レコードでも画像が存在している場合がある
            = f.hidden_field :image_cache
        - else
          = f.file_field :image, class: "filestyle", \
            data: {buttonText: "", size: "sm", icon: "true", \
            buttonBefore: "true", placeholder: "画像ファイルを選択"}
    .form-group
      = f.label :tag_list, "整理ラベル", class: "col-md-2 control-label"
      .col-md-10
        = text_field_tag "recipe[tag_list]", @recipe.tag_list.join(","), data: { role: "tagsinput" }, class: "form-control"
    .form-group
      = f.label :is_public, "閲覧", class: "col-md-2 control-label"
      .col-md-10
        - selection = @recipe.is_clipped? ? { "自分専用（公開不可）": false } : { "みんなに公開": true, "自分専用": false }
        = f.select :is_public, selection, {}, class: "selectpicker"
            
  .recipe-ingredients.sortable.items
    h2 材料
    = f.fields_for :recipe_ingredients do |rif|
      = render "recipe_ingredient_form", f: rif
    = link_to_add_field "材料を追加", f, :recipe_ingredients

  .recipe-steps.sortable.items
    h2 つくりかた
    = f.fields_for :recipe_steps do |rsf|
      = render "recipe_step_form", f: rsf
    = link_to_add_field "ステップを追加", f, :recipe_steps
      
  .row.mar-top-bottom-25
    .col-md-6
      = f.submit (f.object.new_record? ? "作成する" : "更新する"), class: "btn btn-lg btn-warning btn-block"
    .col-md-6
      = link_to "キャンセルする", @recipe, class:"btn btn-lg btn-default btn-block", role: "button"

app/views/recipes/_recipe_ingredient_form.html.slim
.recipe-ingredient.item
  .form-group
    = f.hidden_field :id
    
    .col-md-1.control-label
      span class="badge row_order"
        = f.object.row_order
      = f.hidden_field :row_order, class: "row_order"
    
    .col-md-5
      = f.text_field :name, class: "form-control"
    
    = f.label "数量", class: "col-md-2 control-label"
    
    .col-md-3
      = f.text_field :quantity_for, class: "form-control"

    .col-md-1
      = link_to_remove_field "削除", f

app/views/recipes/_recipe_step_form.html.slim
.recipe-step.item
  .form-group
    = f.hidden_field :id
    
    .col-md-1.control-label
      span class="badge row_order"
        = f.object.row_order
      = f.hidden_field :row_order, class: "row_order"
    
    .col-md-5
      = f.text_area :text, class: "form-control", rows: 10
    
    .col-md-5
      - if f.object.image?
        = image_tag f.object.image_url
        .image_related
          = f.check_box :remove_image
          = f.label :remove_image, "画像を削除", class: "control-label"
          / レシピの取得に（部分的に）失敗した場合、新規レコードで画像が存在している場合がある
          = f.hidden_field :image_cache
      - else
        = f.file_field :image, class: "filestyle", \
          data: {buttonText: "", size: "sm", icon: "true", \
          buttonBefore: "true", placeholder: "画像ファイルを選択"} 

    .col-md-1
      = link_to_remove_field "削除", f

app/views/recipes/_recipes.html.slim
.row
  - if @recipes.any?
      - @recipes.each do |recipe|
        .col-md-4.col-sd-6
          .thumbnail
            - if recipe.is_public
                - if recipe_created_by_other_user? recipe
                  / corner ribbon
                  .corner-ribbon.top-right.success
                    | みんなのレシピ
                - else
                  / corner ribbon
                  .corner-ribbon.top-right.primary
                    | 公開中
            / star / unstar
            div class="action"
              = render partial: "star", locals: { recipe: recipe }
            / image
            - if recipe.image.present?
              - img = image_tag recipe.image_url(:thumb)
            - else
              / holder.js は標準ではsrcを使うがrailsではdata-src
              / FFはsrcが空白だと画像が表示されないので、以下のようにする
              - img = tag :img, data: {src: "holder.js/280x210?text=画像なし&theme=gray"}
            = link_to img, recipe
            / caption
            .caption
              h4 = link_to recipe.title, recipe
              - if recipe.tag_list.present?
                .tags
                  - recipe.tag_list.each do |tag|
                    span class="tag label label-success"
                      = tag
  - else
    .col-md-12
      .alert.alert-info レシピがありません。
.row.text-center
    = paginate @recipes

app/views/recipes/_star.html.slim
- if current_user
  div class="star-#{recipe.id}"
    - if recipe.voted_on_by? current_user
      - star_flag = "starred"
      - link_url = unstar_recipe_path(recipe)
    - else
      - star_flag = "unstarred"
      - link_url = star_recipe_path(recipe)
    = link_to link_url, method: :post, remote: :true do
      span class="star glyphicon glyphicon-star #{star_flag}"

app/views/recipes/edit.html.slim
.container
  .row
    .col-md-3
      .left-sidebar
        .btn-group-vertical.btn-block role="group"
          = link_to "レシピを削除する", recipe_path, method: :delete, data: { confirm: "レシピを削除しますか？" }, class: "btn btn-warning btn-lg", role: "button"
    .col-md-9
      = render 'recipe_form'

app/views/recipes/index.html.slim
.container
  .row
    .page-header.col-md-12
      h1 
        = @is_public.present? ? "みんなのレシピ" : "マイレシピ"
  .row
    .col-md-12
      ul class="nav nav-tabs"
        li class="active"
          a href="#tab1" data-toggle="tab"
            | ワードで検索
        li
          a href="#tab2" data-toggle="tab"
            | ラベルで検索
      .tab-content
        .tab-pane.fade.in.active#tab1
          = render "search_form"
        .tab-pane.fade.in#tab2
          = render "label_form"
      = render "recipes"

app/views/recipes/new.html.slim
.container
  .row
    .col-md-3
      .left-sidebar
    .col-md-9
      = render 'clip_form'
      = render 'recipe_form'

app/views/recipes/star.js.erb
$('.star-<%= @recipe.id %>').replaceWith("<%= escape_javascript(render partial: "star" , locals: { recipe: @recipe }) %>");

app/views/recipes/starred_index.html.slim
.container
  .row
    .page-header.col-md-12
      h1 お気に入りレシピ
  = render "recipes"

app/views/recipes/unstar.js.erb
$('.star-<%= @recipe.id %>').replaceWith("<%= escape_javascript(render partial: "star" , locals: { recipe: @recipe }) %>");