config/routes.rb
Rails.application.routes.draw do
  root to: 'static_pages#home'
  get 'login', to: 'user_sessions#new', as: :login
  delete 'logout', to: 'user_sessions#destroy', as: :logout
  post 'clip', to: "recipes#clip"

  resources :users, except: [:index, :show]
  resources :user_sessions
  resources :recipes do
    member do
      post "star", action: :star
      post "unstar", action: :unstar
    end
    collection do
      get "starred", action: :starred_index
    end
  end

end

app/controllers/user_sessions_controller.rb
class UserSessionsController < ApplicationController
  before_action :require_login, only: [:destroy]

  def new
    @user = User.new
  end

  def create
    if @user = login(params[:email], params[:password], params[:remember])
      redirect_back_or_to controller: :recipes, action: :index
    else
      flash.now[:alert] = "ログインに失敗しました。"
      render "new"
    end
  end

  def destroy
    logout
    redirect_to root_path
  end
end

app/views/user_sessions/_form.html.slim
h1 ログイン

= form_tag user_sessions_path, method: :post do
  .form-group
    = label_tag :email, "メールアドレス"
    = text_field_tag :email, nil, class: "form-control"

  .form-group
    = label_tag :password, "パスワード"
    = password_field_tag :password, nil, class: "form-control"

  .form-group
    = check_box_tag :remember, params[:remember], true
    = label_tag :remember, "ログインしたままにする"

  .actions
    = submit_tag "ログインする", class: "btn btn-lg btn-success"
  
  p
  = link_to "ユーザ登録する", new_user_path

app/views/user_sessions/new.html.slim
.row
  .col-md-6.col-md-offset-3
    = render "form"