config/routes.rb
Rails.application.routes.draw do
  root to: 'static_pages#home'
  get 'login', to: 'user_sessions#new', as: :login
  delete 'logout', to: 'user_sessions#destroy', as: :logout
  post 'clip', to: "recipes#clip"

  resources :users, except: [:index, :show]
  resources :user_sessions
  resources :recipes do
    member do
      post "star", action: :star
      post "unstar", action: :unstar
    end
    collection do
      get "starred", action: :starred_index
    end
  end

end

app/views/layouts/_header.html.erb
<nav class="navbar navbar-default navbar-fixed-top">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle offcanvas-toggle"
        data-toggle="offcanvas" data-target="#js-bootstrap-offcanvas">
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%= link_to root_path, class: "navbar-brand" do %>
        <%= image_tag "main-logo.png" %>
      <% end %>
    </div>
    <div class="navbar-offcanvas navbar-offcanvas-touch" id="js-bootstrap-offcanvas">
      <ul class="nav navbar-nav navbar-right">
        <% if logged_in? %>
            <li><%= link_to "マイレシピ", recipes_path %></li>
            <li><%= link_to "みんなのレシピ", recipes_path(recipe: { is_public: true }) %></li>
            <li><%= link_to "レシピの作成", new_recipe_path %></li>
            <li class="dropdown">
                <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                  <span class="glyphicon glyphicon-user"></span>
                  <%= current_user.name.blank? ? get_name_from_email(current_user.email) : current_user.name %>
                  <b class="caret"></b>
                </a>
                <ul class="dropdown-menu">
                    <li><%= link_to "お気に入りレシピ", starred_recipes_path(recipe: { is_public: true }) %></li>
                    <li role="separator" class="divider"></li>
                    <li><%= link_to "アカウント情報", edit_user_path(current_user) %></li>
                    <li><%= link_to "ログアウト", logout_path, method: "delete" %></li>
                </ul>
            </li>
        <% else %>
            <li><%= link_to "ホーム", root_path %></li>
            <li><%= link_to "みんなのレシピ", recipes_path(recipe: { is_public: true }) %></li>
            <li><%= link_to "ログイン", login_path %></li>
        <% end %>
      </ul>
    </div>
  </div>
</nav>

app/views/layouts/_top_image.html.erb
<div class="jumbotron header">
  <div class="container">
    <h1>Hello</h1>
  </div>  
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Recipee</title>
      <%= stylesheet_link_tag    "application" %>
      <%= javascript_include_tag "application" %>
      <%= csrf_meta_tags %>
      <meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=no" />
  </head>
  <body>
    <%= render "layouts/header" %>
    <div class="container">
      <% flash_messages %>
    </div>
    <%= yield %>
  </body>
</html>